# Generated by Django 4.1.2 on 2022-10-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transaction_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='company_id',
            new_name='company',
        ),
    ]
